#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed 
#four million, find the sum of the even-valued terms.

x=[1,1]
while(x[len(x)-1]<4000000):
	x.append(x[len(x)-1]+x[len(x)-2])

k=sum([i for i in x if(i%2==0)])
print k