<?php

/*  Problem 2: Even Fibonacci numbers
 *  -----
 *  Each new term in the Fibonacci sequence is generated by adding the previous
 *  two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not
 *  exceed four million, find the sum of the even-valued terms.
 */

// loop + swap + mod + accum
$s = 0;
for($i = 1, $j = 2; $i < 4000000; $t = $j, $j += $i, $i = $t)
    if($i % 2 === 0)
        $s += $i;

echo $s; // 4613732

?>
